import type { Locale } from "./types";
const en={title:"AIF-C01 simulation",subtitle:"65 questions · 90 minutes",start:"Start simulation",resume:"Resume simulation",demo:"Static product demo",english:"Original English question content.",minutes:"minutes",domains:"domains",sourceAttribution:"Source & attribution",answered:"Answered",unanswered:"Unanswered",flagged:"Flagged",question:"Question",of:"of",previous:"Previous",next:"Next",flag:"Flag",unflag:"Unflag",submit:"Submit",submitTitle:"Submit this simulation?",submitBody:"Unanswered questions count as incorrect. Answers cannot be changed after submission.",keepWorking:"Keep working",submitNow:"Submit now",confidence:"Confidence",low:"Low",medium:"Medium",high:"High",shortcuts:"Keyboard shortcuts",choose:"choose",navigate:"navigate",openHelp:"shortcut help",close:"Close",result:"Simulation result",rawScore:"raw practice score",timeUsed:"Time used",domainPerformance:"Domain performance",review:"Answer review",correct:"Correct",incorrect:"Incorrect",unscored:"Unscored",recommendations:"Recommended focus",exportMd:"Export AI brief",exportJson:"Export JSON",restart:"Reset demo",delete:"Delete local data",privacy:"Progress stays in this browser. No account, analytics, or server-side collection.",staticWarning:"This static demo includes answer data in its downloadable bundle and is not a secure exam platform.",theme:"Theme",system:"System",light:"Light",dark:"Dark",language:"Language",selectTwo:"Select all correct responses.",arrange:"Arrange every item in the correct order.",match:"Match every item.",confirmReset:"Delete the saved attempt and start again?",ready:"A focused AWS AI Practitioner rehearsal",readyBody:"Complete a full exam-length simulation. Your timer, responses, flags, and report remain only on this device.",domain:"Domain",score:"Score",source:"Source",readiness:"Readiness target: 80%",allAnswered:"All questions answered",menu:"Questions",summary:"Session summary",legalIndependent:"Independent study resource; not affiliated with or endorsed by Amazon Web Services. AWS and related marks are trademarks of Amazon.com, Inc. or its affiliates.",legalAttribution:"Question content adapted from CloudCertPrep under the MIT License. Copyright © 2026 Alex Santonastaso.",legalSource:"View source and license",multipleChoice:"Multiple choice",multipleResponse:"Multiple response",ordering:"Ordering",matching:"Matching",evidence:"Evidence",none:"None"} as const;
const pt:Record<keyof typeof en,string>={
  title:"Simulado AIF-C01",subtitle:"65 questões · 90 minutos",start:"Iniciar simulado",resume:"Continuar simulado",demo:"Demonstração estática",english:"Versão PT-BR comunitária ainda não revisada integralmente. Consulte a documentação oficial da AWS quando um termo parecer ambíguo.",minutes:"minutos",domains:"domínios",sourceAttribution:"Código-fonte e atribuição",
  answered:"Respondidas",unanswered:"Não respondidas",flagged:"Marcadas",question:"Questão",of:"de",previous:"Anterior",next:"Próxima",flag:"Marcar",unflag:"Desmarcar",submit:"Entregar",submitTitle:"Entregar este simulado?",submitBody:"Questões não respondidas contam como incorretas. As respostas não poderão ser alteradas.",keepWorking:"Continuar",submitNow:"Entregar agora",
  confidence:"Confiança",low:"Baixa",medium:"Média",high:"Alta",shortcuts:"Atalhos do teclado",choose:"selecionar",navigate:"navegar",openHelp:"ver atalhos",close:"Fechar",result:"Resultado do simulado",rawScore:"pontuação bruta de prática",timeUsed:"Tempo utilizado",domainPerformance:"Desempenho por domínio",review:"Revisão das respostas",correct:"Correta",incorrect:"Incorreta",unscored:"Não pontuada",recommendations:"Foco recomendado",
  exportMd:"Exportar resumo de estudo para IA",exportJson:"Exportar JSON",restart:"Reiniciar demonstração",delete:"Excluir dados locais",privacy:"O progresso fica salvo neste navegador. Não há conta, métricas de uso ou coleta de dados no servidor.",staticWarning:"Esta demonstração estática inclui as respostas no pacote baixado e não é uma plataforma segura de prova.",theme:"Tema",system:"Sistema",light:"Claro",dark:"Escuro",language:"Idioma",selectTwo:"Selecione todas as respostas corretas.",arrange:"Organize todos os itens na ordem correta.",match:"Associe todos os itens.",confirmReset:"Excluir a tentativa salva e começar novamente?",
  ready:"Uma preparação focada para a certificação AWS AI Practitioner",readyBody:"Faça um simulado completo. Cronômetro, respostas, marcações e relatório permanecem somente neste dispositivo.",domain:"Domínio",score:"Pontuação",source:"Fonte",readiness:"Meta de prontidão: 80%",allAnswered:"Todas as questões respondidas",menu:"Questões",summary:"Resumo da sessão",legalIndependent:"Material de estudo independente, sem afiliação ou endosso da Amazon Web Services. AWS e marcas relacionadas pertencem à Amazon.com, Inc. ou suas afiliadas.",legalAttribution:"Conteúdo adaptado do CloudCertPrep sob a Licença MIT. Copyright © 2026 Alex Santonastaso.",legalSource:"Ver código-fonte e licença",multipleChoice:"Múltipla escolha",multipleResponse:"Múltiplas respostas",ordering:"Ordenação",matching:"Associação",evidence:"Questões para revisar",none:"Nenhuma"
};
export const dictionaries={en,"pt-BR":pt};
export type TranslationKey=keyof typeof en;
export function translate(locale:Locale,key:TranslationKey):string{return dictionaries[locale][key]}
export const domainNames={en:["","Fundamentals of AI and ML","Fundamentals of Generative AI","Applications of Foundation Models","Responsible AI","Security, Compliance, and Governance"],"pt-BR":["","Fundamentos de IA e ML","Fundamentos de IA generativa","Aplicações de modelos de base","IA responsável","Segurança, conformidade e governança"]};
export const questionTypeNames={
  multiple_choice:"multipleChoice",
  multiple_response:"multipleResponse",
  ordering:"ordering",
  matching:"matching",
} as const satisfies Record<"multiple_choice"|"multiple_response"|"ordering"|"matching",TranslationKey>;
